nginx:
  build: ./httpd
  #build: ./nginx
  ports:
    - "9898:80"
  links:
   - appone:web1
   - apptwo:web2
appone:  
  image: 192.168.99.100:8043/hello-docker:1.0.19
  ports:
    - "9876:8080"
  environment:
    - HELLO_MODE=appone
apptwo:  
  image: 192.168.99.100:8043/hello-docker:1.0.19
  ports:
    - "9877:8080"
  environment:
    - HELLO_MODE=apptwo
